<template>
  <div id="app">

    <h1 class="title"> Propagator WebApp</h1>
    <div class="ui error message">
      <div class="header">
        Remains bugs
      </div>
      <ul class="list">
        <li>Do not propagate with default date value ! You need to change it !</li>
        <li>Value are generated by Orekit but I didn't check if it was the good one at the good format.</li>
      </ul>
    </div>
    <PropagatorForm/>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
import PropagatorForm from './components/PropagatorForm.vue'

export default {
  name: 'app',
  components: {
    HelloWorld,
    PropagatorForm
  }
}
</script>

<style>
#app {
margin:50px;
padding-bottom: 100px;
}
.title{
  text-align: center;
  margin-bottom: 50px;
  color: #e8337b;
  opacity: 0.5;
  font-size: 54px;
}
</style>
